baseurl = "http://valekseev.me/"
languageCode = "en-US"
title = "Home"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-114865222-1"
theme = "hugo-sustain"
ignoreFiles = ["wtat-is-next", "optimize-aws", "madness-week"]


[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "avatar.jpg"
  author = "Vladimir Alekseev"
  description = "Home blog"
  website = "valekseev.me"
  website_full = "http://valekseev.me/"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "som3"
  Email         = "valekseev@protonmail.com"
  Twitter       = "Som3t1me5"
  LinkedIn      = "vladimir-alekseev-95ba93b8"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 1
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "resume"
  identifier = "resume"
  weight = 2
  url = "/resume/"


[taxonomies]
tag = "tags"
category = "category"